-- 000086_invoice_smart_label.sql
-- INVOICE-POLISH 6b: enrich the customer-facing invoice label (invoices.notes_*) at
-- creation with the billing PERIOD (class/membership → "Name — Month Year") and the
-- SESSION COUNT (PT → "Name · N sessions"), localized ar/en/fr. The receipt + WhatsApp
-- already render notes_* via invoiceNote(). invoices has NO description_* column — the
-- label lives in notes_* (the field every path already populated + the receipt shows).
--
-- Each RPC below is CREATE OR REPLACE'd from its CURRENT live body
-- (000074/000041/000047/000031) with ONLY the _system_issue_invoice / issue_invoice
-- label arguments changed (generated by extracting the exact body + substituting the
-- label lines, so no later amendment is reverted). register_camp keeps its plain
-- "Camp: name" label — same one-line pattern, deferred to keep this migration bounded.
-- Additive + idempotent (CREATE OR REPLACE); no schema change.


-- Localized "Month YYYY" for the invoice period label (INVOICE-POLISH 6b).
CREATE OR REPLACE FUNCTION _invoice_month_label(d date, lang text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT (CASE extract(month from d)::int
    WHEN 1  THEN CASE lang WHEN 'ar' THEN 'يناير'   WHEN 'fr' THEN 'janvier'   ELSE 'January'   END
    WHEN 2  THEN CASE lang WHEN 'ar' THEN 'فبراير'  WHEN 'fr' THEN 'février'   ELSE 'February'  END
    WHEN 3  THEN CASE lang WHEN 'ar' THEN 'مارس'    WHEN 'fr' THEN 'mars'      ELSE 'March'     END
    WHEN 4  THEN CASE lang WHEN 'ar' THEN 'أبريل'   WHEN 'fr' THEN 'avril'     ELSE 'April'     END
    WHEN 5  THEN CASE lang WHEN 'ar' THEN 'مايو'    WHEN 'fr' THEN 'mai'       ELSE 'May'       END
    WHEN 6  THEN CASE lang WHEN 'ar' THEN 'يونيو'   WHEN 'fr' THEN 'juin'      ELSE 'June'      END
    WHEN 7  THEN CASE lang WHEN 'ar' THEN 'يوليو'   WHEN 'fr' THEN 'juillet'   ELSE 'July'      END
    WHEN 8  THEN CASE lang WHEN 'ar' THEN 'أغسطس'   WHEN 'fr' THEN 'août'      ELSE 'August'    END
    WHEN 9  THEN CASE lang WHEN 'ar' THEN 'سبتمبر'  WHEN 'fr' THEN 'septembre' ELSE 'September' END
    WHEN 10 THEN CASE lang WHEN 'ar' THEN 'أكتوبر'  WHEN 'fr' THEN 'octobre'   ELSE 'October'   END
    WHEN 11 THEN CASE lang WHEN 'ar' THEN 'نوفمبر'  WHEN 'fr' THEN 'novembre'  ELSE 'November'  END
    WHEN 12 THEN CASE lang WHEN 'ar' THEN 'ديسمبر'  WHEN 'fr' THEN 'décembre'  ELSE 'December'  END
  END) || ' ' || extract(year from d)::int::text;
$$;

CREATE OR REPLACE FUNCTION _activate_class_registration(
  p_reg_id UUID, p_discount_pct NUMERIC, p_discount_amount_usd NUMERIC, p_notify_type TEXT
) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_reg     class_registrations;
  v_class   classes;
  v_fee     NUMERIC;
  v_pct     NUMERIC;
  v_amt     NUMERIC;
  v_net     NUMERIC;
  v_net_lbp NUMERIC;
  v_rate    NUMERIC;
  v_rdate   DATE;
  v_inv     invoices;
  v_inv_id  UUID := NULL;
BEGIN
  SELECT * INTO v_reg FROM class_registrations WHERE id = p_reg_id FOR UPDATE;
  SELECT * INTO v_class FROM classes WHERE id = v_reg.class_id;

  v_fee := COALESCE(v_reg.monthly_fee_usd, v_class.monthly_fee_usd, 0);
  v_pct := LEAST(GREATEST(COALESCE(p_discount_pct, 0), 0), 100);     -- E6: % in [0,100]
  v_amt := GREATEST(COALESCE(p_discount_amount_usd, 0), 0);          -- E6: floor 0
  v_net := v_fee * (1 - v_pct / 100.0) - v_amt;
  IF v_net < 0 THEN v_net := 0; END IF;                              -- E6: never below 0

  SELECT rate, rate_date INTO v_rate, v_rdate FROM exchange_rates ORDER BY rate_date DESC LIMIT 1;
  v_net_lbp := CASE WHEN v_rate IS NOT NULL THEN round(v_net * v_rate) ELSE COALESCE(v_reg.monthly_fee_lbp, 0) END;

  -- E5: bill on the active transition (skip when fully discounted / free).
  IF v_net > 0.005 THEN
    v_inv := _system_issue_invoice(
      v_reg.gym_id, v_reg.student_id, 'class_registration', v_net, v_net_lbp, v_rate, v_rdate, NULL,
      (CURRENT_DATE + 14),
      COALESCE(v_class.name_en, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'en'),
      COALESCE(v_class.name_ar, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'ar'),
      COALESCE(v_class.name_fr, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'fr'));
    v_inv_id := v_inv.id;
  END IF;

  UPDATE class_registrations
  SET status = 'active', waitlist_position = NULL,
      discount_pct = v_pct, discount_amount_usd = v_amt,
      start_date = CURRENT_DATE, end_date = (CURRENT_DATE + INTERVAL '1 month')::date,
      invoice_id = v_inv_id, approved_by = auth.uid(), approved_at = now(), updated_at = now()
  WHERE id = p_reg_id;

  -- Project the attendance roster (B1 class_enrollments — unchanged flow).
  INSERT INTO class_enrollments (class_id, student_id, is_active)
  VALUES (v_reg.class_id, v_reg.student_id, true)
  ON CONFLICT (class_id, student_id) DO UPDATE SET is_active = true;

  PERFORM _notify_class_student(
    v_reg.student_id, v_reg.gym_id, p_notify_type,
    -- GO-LIVE-GUARDS: the approval notify shows what the member OWES — the
    -- tax-inclusive invoice total — not the pre-TVA net.
    jsonb_build_object('class', COALESCE(v_class.name_en, v_class.name_ar), 'fee', COALESCE(v_inv.total_usd, v_net)), p_reg_id);

  INSERT INTO audit_logs (table_name, record_id, operation, new_data, changed_by)
  VALUES ('class_registrations', p_reg_id, 'update',
          jsonb_build_object('action', p_notify_type, 'net_usd', v_net, 'invoice', v_inv_id), auth.uid());
END;
$$;
REVOKE ALL ON FUNCTION _activate_class_registration(UUID, NUMERIC, NUMERIC, TEXT) FROM PUBLIC;

CREATE OR REPLACE FUNCTION sell_pt_package(
  p_student_id          UUID,
  p_package_id          UUID,
  p_coach_id            UUID,
  p_discount_pct        NUMERIC DEFAULT 0,
  p_discount_amount_usd NUMERIC DEFAULT 0,
  p_request_id          UUID DEFAULT NULL
) RETURNS pt_assignments
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_pkg     pt_packages;
  v_student students;
  v_req     pt_assignments;
  v_a       pt_assignments;
  v_net     NUMERIC;
  v_rate    NUMERIC;
  v_rdate   DATE;
  v_lbp     NUMERIC;
  v_inv     invoices;
  v_expires TIMESTAMPTZ;
  v_name    TEXT;
BEGIN
  IF NOT is_staff() THEN RAISE EXCEPTION 'Only staff may sell PT packages'; END IF;

  SELECT * INTO v_pkg FROM pt_packages WHERE id = p_package_id;
  IF v_pkg.id IS NULL THEN RAISE EXCEPTION 'Package type % not found', p_package_id; END IF;
  IF v_pkg.gym_id <> get_user_gym_id() THEN RAISE EXCEPTION 'Package type is not in your gym'; END IF;
  IF NOT v_pkg.is_active OR v_pkg.deleted_at IS NOT NULL THEN RAISE EXCEPTION 'Package type is archived'; END IF;

  SELECT * INTO v_student FROM students WHERE id = p_student_id;
  IF v_student.id IS NULL THEN RAISE EXCEPTION 'Member % not found', p_student_id; END IF;
  IF v_student.gym_id <> v_pkg.gym_id THEN RAISE EXCEPTION 'Member and package are in different gyms'; END IF;
  IF NOT v_student.is_active THEN RAISE EXCEPTION 'Member is not active'; END IF;

  -- Coach: MANDATORY for a desk sale (allocation binds at sale, §3); the 22R
  -- approval path (p_request_id) may carry NULL — the legacy request semantics
  -- where the coach binds at scheduling (schedule_pt_session requires one).
  IF p_request_id IS NULL AND p_coach_id IS NULL THEN
    RAISE EXCEPTION 'A coach is required for a PT sale';
  END IF;
  IF p_coach_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM coaches WHERE id = p_coach_id AND gym_id = v_pkg.gym_id AND is_active AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Coach is not an active coach of this gym';
  END IF;

  IF COALESCE(p_discount_pct, 0) < 0 OR COALESCE(p_discount_pct, 0) > 100 THEN
    RAISE EXCEPTION 'Discount percent must be between 0 and 100';
  END IF;

  -- Discount discipline (B2 idiom): % then fixed, floor at zero.
  v_net := GREATEST(0, round(v_pkg.price_usd * (1 - COALESCE(p_discount_pct, 0) / 100), 2)
                        - COALESCE(p_discount_amount_usd, 0));
  v_expires := CASE WHEN v_pkg.validity_days IS NOT NULL
                    THEN now() + make_interval(days => v_pkg.validity_days) END;

  IF p_request_id IS NOT NULL THEN
    -- 22R approval path: ACTIVATE the member's requested row (same writer).
    SELECT * INTO v_req FROM pt_assignments WHERE id = p_request_id FOR UPDATE;
    IF v_req.id IS NULL THEN RAISE EXCEPTION 'Request % not found', p_request_id; END IF;
    IF v_req.status <> 'requested' THEN RAISE EXCEPTION 'Request is not pending (status %)', v_req.status; END IF;
    IF v_req.student_id <> p_student_id OR v_req.package_id <> p_package_id THEN
      RAISE EXCEPTION 'Request does not match the member/package';
    END IF;
    UPDATE pt_assignments
    SET status = 'active', is_active = true, coach_id = COALESCE(p_coach_id, coach_id),
        sessions_total = v_pkg.session_count, sessions_used = 0,
        purchased_at = now(), expires_at = v_expires,
        approved_by = auth.uid(), approved_at = now(), updated_at = now()
    WHERE id = p_request_id
    RETURNING * INTO v_a;
  ELSE
    INSERT INTO pt_assignments (
      student_id, package_id, coach_id, sessions_total, sessions_used,
      status, is_active, purchased_at, expires_at, approved_by, approved_at
    )
    VALUES (
      p_student_id, p_package_id, p_coach_id, v_pkg.session_count, 0,
      'active', true, now(), v_expires, auth.uid(), now()
    )
    RETURNING * INTO v_a;
  END IF;

  -- Invoice via the canonical issuance path (number/TVA triggers; payer
  -- auto-resolves to the primary guardian for linked minors — B3).
  IF v_net > 0.005 THEN
    SELECT rate, rate_date INTO v_rate, v_rdate FROM exchange_rates ORDER BY rate_date DESC LIMIT 1;
    v_lbp := CASE WHEN v_rate IS NOT NULL THEN round(v_net * v_rate) ELSE COALESCE(v_pkg.price_lbp, 0) END;
    v_inv := _system_issue_invoice(
      v_pkg.gym_id, p_student_id, 'pt_package', v_net, v_lbp, v_rate, v_rdate, NULL, NULL,
      COALESCE(v_pkg.name_en, '') || ' · ' || v_pkg.session_count || ' sessions',
      COALESCE(v_pkg.name_ar, '') || ' · ' || v_pkg.session_count || ' حصص',
      COALESCE(v_pkg.name_fr, '') || ' · ' || v_pkg.session_count || ' séances',
      NULL);
    UPDATE pt_assignments SET invoice_id = v_inv.id, updated_at = now() WHERE id = v_a.id
    RETURNING * INTO v_a;
  END IF;

  -- Best-effort notifications (member approved/sold + coach assigned) — the
  -- F2 pattern; login-less members have no auth row, so never fail the sale.
  BEGIN
    SELECT COALESCE(p.first_name_en, p.first_name_ar, '') INTO v_name
    FROM profiles p WHERE p.id = v_student.profile_id;
    INSERT INTO notifications (user_id, gym_id, type, title_key, body_key, params, entity_type, entity_id, action_url)
    VALUES (v_student.profile_id, v_pkg.gym_id, 'pt_approved',
            'messages.pt_approved.title', 'messages.pt_approved.body',
            jsonb_build_object('package', COALESCE(v_pkg.name_en, v_pkg.name_ar), 'count', v_a.sessions_total),
            'pt_assignment', v_a.id, '/portal/pt');
  EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN
    INSERT INTO notifications (user_id, gym_id, type, title_key, body_key, params, entity_type, entity_id, action_url)
    SELECT c.profile_id, v_pkg.gym_id, 'pt_assigned',
           'messages.pt_assigned.title', 'messages.pt_assigned.body',
           jsonb_build_object('count', v_a.sessions_total),
           'pt_assignment', v_a.id, '/coach/pt'
    FROM coaches c WHERE c.id = p_coach_id AND c.profile_id IS NOT NULL;
  EXCEPTION WHEN OTHERS THEN NULL; END;

  RETURN v_a;
END;
$$;
REVOKE ALL ON FUNCTION sell_pt_package(UUID, UUID, UUID, NUMERIC, NUMERIC, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION sell_pt_package(UUID, UUID, UUID, NUMERIC, NUMERIC, UUID) TO authenticated;

CREATE OR REPLACE FUNCTION _issue_membership_renewal(p_membership_id UUID)
RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_m      student_memberships;
  v_s      students;
  v_plan   membership_plans;
  v_start  DATE;
  v_end    DATE;
  v_inv    invoices;
  v_rate   NUMERIC;
  v_rdate  DATE;
  v_lbp    NUMERIC;
BEGIN
  SELECT * INTO v_m FROM student_memberships WHERE id = p_membership_id FOR UPDATE;
  IF v_m.id IS NULL OR v_m.status NOT IN ('active', 'lapsed', 'expired') THEN RETURN NULL; END IF;
  SELECT * INTO v_s FROM students WHERE id = v_m.student_id;
  -- Price/duration honor a pending NEXT-CYCLE plan change at ISSUE time.
  SELECT * INTO v_plan FROM membership_plans WHERE id = COALESCE(v_m.pending_plan_id, v_m.plan_id);

  v_start := v_m.end_date;
  v_end   := v_m.end_date + v_plan.duration_days;
  -- Idempotency: one renewal per period, enforced by the unique link.
  IF EXISTS (SELECT 1 FROM renewal_invoices
             WHERE product_type = 'membership' AND product_id = v_m.id AND period_start = v_start) THEN
    RETURN NULL;
  END IF;

  SELECT rate, rate_date INTO v_rate, v_rdate FROM exchange_rates ORDER BY rate_date DESC LIMIT 1;
  v_lbp := CASE WHEN v_rate IS NOT NULL THEN round(v_plan.price_usd * v_rate) ELSE COALESCE(v_plan.price_lbp, 0) END;
  v_inv := _system_issue_invoice(
    v_s.gym_id, v_m.student_id, 'membership', v_plan.price_usd, v_lbp, v_rate, v_rdate,
    v_m.id, v_start,
    COALESCE(v_plan.name_en, '') || ' — ' || _invoice_month_label(v_start, 'en'),
    COALESCE(v_plan.name_ar, '') || ' — ' || _invoice_month_label(v_start, 'ar'),
    COALESCE(v_plan.name_fr, '') || ' — ' || _invoice_month_label(v_start, 'fr'),
    NULL);

  INSERT INTO renewal_invoices (invoice_id, product_type, product_id, period_start, period_end)
  VALUES (v_inv.id, 'membership', v_m.id, v_start, v_end);

  -- Member nudge (dedup-guarded; login-less members have no auth row).
  BEGIN
    INSERT INTO notifications (user_id, gym_id, type, title_key, body_key, params, entity_type, entity_id, action_url, dedup_key)
    VALUES (v_s.profile_id, v_s.gym_id, 'renewal_due',
            'messages.renewal_due.title', 'messages.renewal_due.body',
            jsonb_build_object('amount', v_inv.total_usd, 'date', v_start),
            'invoice', v_inv.id, '/portal/billing',
            'renewal_membership_' || v_m.id || '_' || v_start)
    ON CONFLICT (dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING;
  EXCEPTION WHEN OTHERS THEN NULL; END;

  RETURN v_inv.id;
END;
$$;
REVOKE ALL ON FUNCTION _issue_membership_renewal(UUID) FROM PUBLIC;

CREATE OR REPLACE FUNCTION _issue_registration_renewal(p_reg_id UUID)
RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_r     class_registrations;
  v_s     students;
  v_cls   classes;
  v_net   NUMERIC;
  v_start DATE;
  v_end   DATE;
  v_inv   invoices;
  v_rate  NUMERIC;
  v_rdate DATE;
  v_lbp   NUMERIC;
BEGIN
  SELECT * INTO v_r FROM class_registrations WHERE id = p_reg_id FOR UPDATE;
  IF v_r.id IS NULL OR v_r.status NOT IN ('active', 'suspended') THEN RETURN NULL; END IF;
  SELECT * INTO v_s FROM students WHERE id = v_r.student_id;
  SELECT * INTO v_cls FROM classes WHERE id = v_r.class_id;

  v_start := COALESCE(v_r.paid_until, COALESCE(v_r.start_date, v_r.requested_at::date) + 30);
  v_end   := v_start + 30;
  IF EXISTS (SELECT 1 FROM renewal_invoices
             WHERE product_type = 'class_registration' AND product_id = v_r.id AND period_start = v_start) THEN
    RETURN NULL;
  END IF;

  -- The B2 net-fee discipline (same formula approve used: % then fixed, floor 0).
  v_net := GREATEST(0, round(COALESCE(v_r.monthly_fee_usd, v_cls.monthly_fee_usd, 0)
                             * (1 - COALESCE(v_r.discount_pct, 0) / 100), 2)
                       - COALESCE(v_r.discount_amount_usd, 0));
  IF v_net <= 0.005 THEN RETURN NULL; END IF; -- fully discounted: nothing to bill

  SELECT rate, rate_date INTO v_rate, v_rdate FROM exchange_rates ORDER BY rate_date DESC LIMIT 1;
  v_lbp := CASE WHEN v_rate IS NOT NULL THEN round(v_net * v_rate) ELSE 0 END;
  v_inv := _system_issue_invoice(
    v_s.gym_id, v_r.student_id, 'class_registration', v_net, v_lbp, v_rate, v_rdate,
    NULL, v_start,
    COALESCE(v_cls.name_en, '') || ' — ' || _invoice_month_label(v_start, 'en'),
    COALESCE(v_cls.name_ar, '') || ' — ' || _invoice_month_label(v_start, 'ar'),
    COALESCE(v_cls.name_fr, '') || ' — ' || _invoice_month_label(v_start, 'fr'),
    NULL);

  INSERT INTO renewal_invoices (invoice_id, product_type, product_id, period_start, period_end)
  VALUES (v_inv.id, 'class_registration', v_r.id, v_start, v_end);

  BEGIN
    INSERT INTO notifications (user_id, gym_id, type, title_key, body_key, params, entity_type, entity_id, action_url, dedup_key)
    VALUES (v_s.profile_id, v_s.gym_id, 'renewal_due',
            'messages.renewal_due.title', 'messages.renewal_due.body',
            jsonb_build_object('amount', v_inv.total_usd, 'date', v_start),
            'invoice', v_inv.id, '/portal/billing',
            'renewal_registration_' || v_r.id || '_' || v_start)
    ON CONFLICT (dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING;
  EXCEPTION WHEN OTHERS THEN NULL; END;

  RETURN v_inv.id;
END;
$$;
REVOKE ALL ON FUNCTION _issue_registration_renewal(UUID) FROM PUBLIC;

CREATE OR REPLACE FUNCTION convert_lead_to_member(
  p_lead_id UUID,
  p_plan_id UUID
) RETURNS TABLE (
  student_id     UUID,
  profile_id     UUID,
  membership_id  UUID,
  invoice_id     UUID,
  invoice_number TEXT,
  total_usd      NUMERIC
)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_gym          UUID;
  v_lead         leads;
  v_plan         membership_plans;
  v_profile_id   UUID;
  v_student_id   UUID;
  v_membership_id UUID;
  v_inv          invoices;
  v_rate         NUMERIC;
  v_rate_date    DATE;
BEGIN
  IF NOT is_staff() THEN RAISE EXCEPTION 'Only staff may convert leads'; END IF;
  v_gym := get_user_gym_id();
  IF v_gym IS NULL THEN RAISE EXCEPTION 'No gym context for caller'; END IF;

  SELECT * INTO v_lead FROM leads WHERE id = p_lead_id AND gym_id = v_gym;
  IF v_lead.id IS NULL THEN RAISE EXCEPTION 'Lead % not found in this gym', p_lead_id; END IF;
  IF v_lead.status = 'converted' OR v_lead.converted_student_id IS NOT NULL THEN
    RAISE EXCEPTION 'Lead % is already converted', p_lead_id;
  END IF;

  SELECT * INTO v_plan FROM membership_plans
  WHERE id = p_plan_id AND gym_id = v_gym AND is_active = true;
  IF v_plan.id IS NULL THEN RAISE EXCEPTION 'Membership plan % not found or inactive in this gym', p_plan_id; END IF;

  INSERT INTO profiles (gym_id, first_name_ar, first_name_en, first_name_fr, last_name_ar, last_name_en, last_name_fr, phone)
  VALUES (v_gym, v_lead.first_name, v_lead.first_name, v_lead.first_name,
          v_lead.last_name, v_lead.last_name, v_lead.last_name, v_lead.phone)
  RETURNING id INTO v_profile_id;

  INSERT INTO students (profile_id, gym_id, join_date, is_active, current_belt_rank)
  VALUES (v_profile_id, v_gym, CURRENT_DATE, true, 'white')
  RETURNING id INTO v_student_id;

  INSERT INTO student_memberships (student_id, plan_id, start_date, end_date, status)
  VALUES (v_student_id, v_plan.id, CURRENT_DATE, CURRENT_DATE + v_plan.duration_days, 'active')
  RETURNING id INTO v_membership_id;

  SELECT rate, rate_date INTO v_rate, v_rate_date FROM exchange_rates ORDER BY rate_date DESC LIMIT 1;

  -- D1 retrofit: issue through the canonical service (fires invoice_issued).
  v_inv := issue_invoice(
    v_gym, v_student_id, 'membership', v_plan.price_usd, COALESCE(v_plan.price_lbp, 0),
    v_rate, v_rate_date, v_membership_id, CURRENT_DATE + 14,
    COALESCE(v_plan.name_en, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'en'),
    COALESCE(v_plan.name_ar, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'ar'),
    COALESCE(v_plan.name_fr, '') || ' — ' || _invoice_month_label(CURRENT_DATE, 'fr'));

  UPDATE leads
  SET converted_student_id = v_student_id, status = 'converted', converted_at = now(), updated_at = now()
  WHERE id = p_lead_id;

  RETURN QUERY
  SELECT v_student_id, v_profile_id, v_membership_id, v_inv.id, v_inv.invoice_number::TEXT, v_inv.total_usd::NUMERIC;
END;
$$;
GRANT EXECUTE ON FUNCTION convert_lead_to_member(UUID, UUID) TO authenticated;
